/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configurafacil.presentation;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import configurafacil.business.ConfiguraFacilFacade;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

public class EscolherPacote extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    
    private static ConfiguraFacilFacade facade;
    /**
     * Creates new form EscolherPacote
     */
    public EscolherPacote(java.awt.Frame parent, boolean modal, ConfiguraFacilFacade facade) {
        super(parent, modal);
        initComponents();
        this.facade = facade;

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pacoteSport = new javax.swing.JRadioButton();
        pacoteConfort = new javax.swing.JRadioButton();
        pacoteEconomico = new javax.swing.JRadioButton();
        semPacote = new javax.swing.JRadioButton();
        seguinte = new javax.swing.JButton();
        retroceder = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ConfiguraFacil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Pretende escolher algum dos Pacotes disponíveis?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Selecione a opção que pretende:");

        buttonGroup.add(pacoteSport);
        pacoteSport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pacoteSport.setText("Pacote Sport");
        pacoteSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacoteSportActionPerformed(evt);
            }
        });

        buttonGroup.add(pacoteConfort);
        pacoteConfort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pacoteConfort.setText("Pacote Confort");
        pacoteConfort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacoteConfortActionPerformed(evt);
            }
        });

        buttonGroup.add(pacoteEconomico);
        pacoteEconomico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pacoteEconomico.setText("Pacote Económico");
        pacoteEconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacoteEconomicoActionPerformed(evt);
            }
        });

        buttonGroup.add(semPacote);
        semPacote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semPacote.setText("Sem Pacote");
        semPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semPacoteActionPerformed(evt);
            }
        });

        seguinte.setText("Seguinte");
        seguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguinteActionPerformed(evt);
            }
        });

        retroceder.setText("Retroceder");
        retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrocederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pacoteConfort)
                            .addComponent(pacoteSport)
                            .addComponent(pacoteEconomico)
                            .addComponent(semPacote))))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(retroceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seguinte)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(pacoteSport)
                .addGap(18, 18, 18)
                .addComponent(pacoteConfort)
                .addGap(18, 18, 18)
                .addComponent(pacoteEconomico)
                .addGap(18, 18, 18)
                .addComponent(semPacote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seguinte)
                    .addComponent(retroceder))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void pacoteConfortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacoteConfortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacoteConfortActionPerformed

    private void semPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semPacoteActionPerformed

    private void pacoteSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacoteSportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacoteSportActionPerformed

    private void pacoteEconomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacoteEconomicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacoteEconomicoActionPerformed

    private void retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrocederActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this,"Deseja Retroceder?","Confirmação",YES_NO_OPTION);
        
        if(opcao == 0){
            this.dispose();
            facade.resetComponente("pintura");
            facade.resetComponente("motorizacao");
            EscolherBasicos escolher = new EscolherBasicos(new javax.swing.JFrame(),
                                                      true, facade);
            escolher.setVisible(true);
        }
    }//GEN-LAST:event_retrocederActionPerformed

    private void seguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguinteActionPerformed
        if(pacoteSport.isSelected()){
            if(!facade.verificaPacote(facade.getPacote(1))){
                        facade.addCompPacoteToList(facade.getPacote(1)); 
                        facade.addPacoteConfiguracao(facade.getPacote(1)); 
                        this.dispose();
                        FinalizaConfiguracao finaliza = new FinalizaConfiguracao(new javax.swing.JFrame(),
                                                      true, facade);
                        finaliza.setVisible(true);
            }else{
                         String msg = "Pacote incompatível com componentes já selecionados. Tente novamente.";
                         JOptionPane.showMessageDialog(this, msg);
            }
            
        }else if(pacoteConfort.isSelected()){
                  if(!facade.verificaPacote(facade.getPacote(2))){
                        facade.addCompPacoteToList(facade.getPacote(2)); 
                        facade.addPacoteConfiguracao(facade.getPacote(2)); 
                        this.dispose();
                        FinalizaConfiguracao finaliza = new FinalizaConfiguracao(new javax.swing.JFrame(),
                                                      true, facade);
                        finaliza.setVisible(true);
                    } else{
                         String msg = "Pacote incompatível com componentes já selecionados. Tente novamente.";
                         JOptionPane.showMessageDialog(this, msg);
                  }
            }else if(pacoteEconomico.isSelected()){
                     if(!facade.verificaPacote(facade.getPacote(3))){
                        facade.addCompPacoteToList(facade.getPacote(3)); 
                        facade.addPacoteConfiguracao(facade.getPacote(3)); 
                        this.dispose();
                        FinalizaConfiguracao finaliza = new FinalizaConfiguracao(new javax.swing.JFrame(),
                                                      true, facade);
                        finaliza.setVisible(true);
                    } else{
                         String msg = "Pacote incompatível com componentes já selecionados. Tente novamente.";
                         JOptionPane.showMessageDialog(this, msg);
                  }
                }else if(semPacote.isSelected()){
                           facade.addPacoteConfiguracao(null); 
                           this.dispose();
                           EscolherJPS jps = new EscolherJPS(new javax.swing.JFrame(),
                                                      true, facade);
                           jps.setVisible(true);
                           this.dispose();
                           
                }else{
                    String msg = "Tem que selecionar uma opção";
                    JOptionPane.showMessageDialog(this, msg);
                }
    }//GEN-LAST:event_seguinteActionPerformed
    
    
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton pacoteConfort;
    private javax.swing.JRadioButton pacoteEconomico;
    private javax.swing.JRadioButton pacoteSport;
    private javax.swing.JButton retroceder;
    private javax.swing.JButton seguinte;
    private javax.swing.JRadioButton semPacote;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
